### ISSUE TITLE
Participants carry objects

### ISSUE THREAD

**Issue by jessesnyder** [Dallinger/Griduniverse#249]
## Story

As a participant, I can pick up and carry with me items marked `portable`. I can only carry a single item at a time (verify!), but I can swap the item currently in my hand for another `portable` item.

## Task Breakdown

- [ ] "In hand" state, both client and server
- [ ] UI for tracking what's in your hand
- [ ] Implicit transition available when occupying square with `portable` item
